# Generated by Django 6.0.6 on 2026-06-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('genero', models.CharField(blank=True, max_length=50, verbose_name='género musical')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(verbose_name='data de fim')),
                ('artistas', models.ManyToManyField(blank=True, related_name='festivais', to='festivais.artista')),
            ],
            options={
                'ordering': ('data_inicio', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Palco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palcos', to='festivais.festival')),
            ],
            options={
                'ordering': ('festival', 'nome'),
                'constraints': [models.UniqueConstraint(fields=('festival', 'nome'), name='palco_nome_unico_por_festival')],
            },
        ),
    ]
